In [1]:
from tensorflow.keras.preprocessing.text import one_hot

Matplotlib is building the font cache; this may take a moment.


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2227, 1815, 3542, 546],
 [2227, 1815, 3542, 6561],
 [2227, 5419, 3542, 901],
 [5286, 4745, 2183, 4025, 9814],
 [5286, 4745, 2183, 4025, 1483],
 [2270, 2227, 6682, 3542, 7498],
 [4772, 3132, 8649, 4025]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2227 1815 3542  546]
 [   0    0    0    0 2227 1815 3542 6561]
 [   0    0    0    0 2227 5419 3542  901]
 [   0    0    0 5286 4745 2183 4025 9814]
 [   0    0    0 5286 4745 2183 4025 1483]
 [   0    0    0 2270 2227 6682 3542 7498]
 [   0    0    0    0 4772 3132 8649 4025]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

e:\AI Engineer Preparation\Latest_Pyton_Env\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step


array([[[ 4.92317565e-02,  4.51794900e-02, -2.96891090e-02,
          4.45157923e-02,  4.04378809e-02, -2.27786060e-02,
          4.07729633e-02,  7.36929476e-04,  1.71758048e-02,
          2.63199098e-02],
        [ 4.92317565e-02,  4.51794900e-02, -2.96891090e-02,
          4.45157923e-02,  4.04378809e-02, -2.27786060e-02,
          4.07729633e-02,  7.36929476e-04,  1.71758048e-02,
          2.63199098e-02],
        [ 4.92317565e-02,  4.51794900e-02, -2.96891090e-02,
          4.45157923e-02,  4.04378809e-02, -2.27786060e-02,
          4.07729633e-02,  7.36929476e-04,  1.71758048e-02,
          2.63199098e-02],
        [ 4.92317565e-02,  4.51794900e-02, -2.96891090e-02,
          4.45157923e-02,  4.04378809e-02, -2.27786060e-02,
          4.07729633e-02,  7.36929476e-04,  1.71758048e-02,
          2.63199098e-02],
        [-6.47666305e-03,  4.51724641e-02, -2.39291079e-02,
          3.40119712e-02,  1.59009732e-02,  3.30633037e-02,
          3.20330895e-02, -3.27209458e-02, -2.086406

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2227, 1815, 3542,  546], dtype=int32)

In [17]:
#model.predict(embedded_docs[0][0])